[font]
size = 10.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
padding = { x = 15, y = 15 }
opacity = 0.5
decorations = "None"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "Always"
